-- Alle Flugzeuge der Lufthansa
SELECT PLANE.MODEL, AIRLINE.NAME
FROM PLANE JOIN AIRLINE ON PLANE.AIRLINE = AIRLINE.ID
WHERE AIRLINE.NAME = 'Lufthansa';

-- Seltentes Flugzeug
SELECT PLANE.MODEL, COUNT(PLANE.MODEL)
FROM PLANE LEFT JOIN FLIGHT ON PLANE.ID = FLIGHT.PLANE
GROUP BY PLANE.MODEL
ORDER BY COUNT(PLANE.MODEL);

-- Meisten Flugstunden
SELECT FIRSTNAME, LASTNAME, FLIGHT_HOURS
FROM PILOT
ORDER BY FLIGHT_HOURS DESC;

-- Piloten gruppiert nach lizenz
SELECT LICENSE_TYPE, COUNT(*)
FROM PILOT
GROUP BY LICENSE_TYPE;

-- Flugzeuge die im Hangar sind
SELECT PLANE.MODEL, AIRLINE.NAME, PLANE.STATUS
FROM PLANE JOIN AIRLINE ON PLANE.AIRLINE = AIRLINE.ID
WHERE PLANE.STATUS = 'MAINTENANCE';

-- Häufigster Ursprungsflughafen
SELECT AIRPORT."NAME", COUNT(*)
FROM FLIGHT JOIN AIRPORT ON FLIGHT."FROM" = AIRPORT.ID
WHERE AIRPORT."NAME" != 'Minden Airport'
GROUP BY AIRPORT."NAME"
ORDER BY COUNT(*) DESC;

-- Airlines mit den meisten Verspätungen
SELECT AIRLINE.NAME, COUNT(*)
FROM AIRLINE JOIN PLANE ON PLANE.AIRLINE = AIRLINE.ID JOIN FLIGHT ON FLIGHT.PLANE = PLANE.ID
WHERE FLIGHT.STATUS = 5
GROUP BY AIRLINE.NAME;

SELECT 
    TICKET.ID,
    TICKET.SEAT_NUMBER,
    FLIGHT."FROM",
    FLIGHT."TO",
    TO_CHAR(TICKET.BOOKING_DATE,'dd.mm.yyyy HH24:MI') AS BOOKING_DATE,
    CASE 
        WHEN FLIGHT.SCHEDULED_DEPARTURE = FLIGHT.ACTUAL_DEPARTURE 
        THEN TO_CHAR(FLIGHT.SCHEDULED_DEPARTURE, 'dd.mm.yyyy HH24:MI')
        ELSE TO_CHAR(FLIGHT.ACTUAL_DEPARTURE, 'dd.mm.yyyy HH24:MI')
    END AS DEPARTURE_TIME,
    TRAVEL_CLASS.NAME AS TRAVEL_CLASS,
    TICKET.PRICE,
    FLIGHT.GATE,
    FLIGHT.BAGGAGE_CLAIM,
    TICKET.STATUS
FROM FLIGHT 
RIGHT JOIN TICKET ON TICKET.FLIGHT = FLIGHT.ID
RIGHT JOIN TRAVEL_CLASS ON TICKET.TRAVEL_CLASS = TRAVEL_CLASS.ID
WHERE TICKET.AirportUser = 'U001';
