version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: minden_backend
    environment:
      - CONNECTIONSTRING=MindenAirport/AbuHatem@ORCL
      - JWT_SECRET=your_jwt_secret_here_change_in_production
      - GIN_MODE=release
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - minden-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Frontend Web App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: minden_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - minden-network

networks:
  minden-network:
    driver: bridge
