-- Beispiel-Datensätze für die Tabelle AIRLINE
INSERT ALL
    INTO AIRLINE ("NAME", "ID", COUNTRY, ACTIVE) VALUES ('Lufthansa', 'LH', 'Germany', 1)
    INTO AIRLINE ("NAME", "ID", COUNTRY, ACTIVE) VALUES ('United Airlines', 'UA', 'United States', 1)
    INTO AIRLINE ("NAME", "ID", COUNTRY, ACTIVE) VALUES ('Emirates', 'EK', 'United Arab Emirates', 1)
    INTO AIRLINE ("NAME", "ID", COUNTRY, ACTIVE) VALUES ('Air France', 'AF', 'France', 1)
    INTO AIRLINE ("NAME", "ID", COUNTRY, ACTIVE) VALUES ('Air Berlin', 'AB', 'Germany', 0)
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle AIRPORT
INSERT ALL
    INTO AIRPORT ("NAME", "ID", COUNTRY, CITY, TIMEZONE, ELEVATION, NUMBER_OF_TERMINALS, LATITUDE, LONGITUDE) VALUES ('Minden Airport', 'MIN', 'Germany', 'Minden', 'UTC+1', 70, 2, 52.285, 8.918)
    INTO AIRPORT ("NAME", "ID", COUNTRY, CITY, TIMEZONE, ELEVATION, NUMBER_OF_TERMINALS, LATITUDE, LONGITUDE) VALUES ('Frankfurt Airport', 'FRA', 'Germany', 'Frankfurt', 'UTC+1', 111, 2, 50.033, 8.570)
    INTO AIRPORT ("NAME", "ID", COUNTRY, CITY, TIMEZONE, ELEVATION, NUMBER_OF_TERMINALS, LATITUDE, LONGITUDE) VALUES ('John F. Kennedy International Airport', 'JFK', 'United States', 'New York', 'UTC-5', 4, 6, 40.639, -73.778)
    INTO AIRPORT ("NAME", "ID", COUNTRY, CITY, TIMEZONE, ELEVATION, NUMBER_OF_TERMINALS, LATITUDE, LONGITUDE) VALUES ('Charles de Gaulle Airport', 'CDG', 'France', 'Paris', 'UTC+1', 119, 3, 49.004, 2.571)
    INTO AIRPORT ("NAME", "ID", COUNTRY, CITY, TIMEZONE, ELEVATION, NUMBER_OF_TERMINALS, LATITUDE, LONGITUDE) VALUES ('Dubai International Airport', 'DXB', 'United Arab Emirates', 'Dubai', 'UTC+4', 19, 3, 25.252, 55.364)
    INTO AIRPORT ("NAME", "ID", COUNTRY, CITY, TIMEZONE, ELEVATION, NUMBER_OF_TERMINALS, LATITUDE, LONGITUDE) VALUES ('Munich Airport', 'MUC', 'Germany', 'Munich', 'UTC+1', 453, 2, 48.136, 11.687)
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle FLIGHT_STATUS
INSERT ALL
    INTO FLIGHT_STATUS ("ID", "NAME", DESCRIPTION) VALUES (1, 'SCHEDULED', 'Flight is scheduled to depart at the planned time')
    INTO FLIGHT_STATUS ("ID", "NAME", DESCRIPTION) VALUES (2, 'BOARDING', 'Passengers are currently boarding the aircraft')
    INTO FLIGHT_STATUS ("ID", "NAME", DESCRIPTION) VALUES (3, 'DEPARTED', 'Flight has taken off and is en route to destination')
    INTO FLIGHT_STATUS ("ID", "NAME", DESCRIPTION) VALUES (4, 'ARRIVED', 'Flight has landed at its destination')
    INTO FLIGHT_STATUS ("ID", "NAME", DESCRIPTION) VALUES (5, 'DELAYED', 'Flight is delayed from its original schedule')
    INTO FLIGHT_STATUS ("ID", "NAME", DESCRIPTION) VALUES (6, 'CANCELLED', 'Flight has been cancelled')
    INTO FLIGHT_STATUS ("ID", "NAME", DESCRIPTION) VALUES (7, 'DIVERTED', 'Flight has been diverted to an alternative airport')
    INTO FLIGHT_STATUS ("ID", "NAME", DESCRIPTION) VALUES (8, 'CHECK_IN', 'Check-in is open for this flight')
    INTO FLIGHT_STATUS ("ID", "NAME", DESCRIPTION) VALUES (9, 'FINAL_CALL', 'Final boarding call for passengers')
    INTO FLIGHT_STATUS ("ID", "NAME", DESCRIPTION) VALUES (10, 'MAINTENANCE', 'Flight is delayed due to aircraft maintenance')
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle TRAVEL_CLASS
INSERT ALL
    INTO TRAVEL_CLASS ("ID", "NAME", DESCRIPTION) VALUES ('1','First Class','Premium cabin experience with maximum comfort, exclusive services, fully-flat beds, gourmet dining, and dedicated check-in')
    INTO TRAVEL_CLASS ("ID", "NAME", DESCRIPTION) VALUES ('2','Business Class','Enhanced travel experience with lie-flat seats, premium meals, lounge access, and priority boarding')
    INTO TRAVEL_CLASS ("ID", "NAME", DESCRIPTION) VALUES ('3','Premium Economy','Extra legroom, wider seats, enhanced meal service, and additional baggage allowance compared to Economy')
    INTO TRAVEL_CLASS ("ID", "NAME", DESCRIPTION) VALUES ('4','Economy','Standard cabin service with comfortable seating, complimentary meals on long-haul flights, and in-flight entertainment')
    INTO TRAVEL_CLASS ("ID", "NAME", DESCRIPTION) VALUES ('5','Basic Economy','Cost-effective option with standard seating, limited flexibility, and basic amenities')
    INTO TRAVEL_CLASS ("ID", "NAME", DESCRIPTION) VALUES ('6','Economy Plus','Economy seating with extra legroom, priority boarding, and additional baggage allowance')
    INTO TRAVEL_CLASS ("ID", "NAME", DESCRIPTION) VALUES ('7','Business First','Hybrid of First and Business class offering premium services with lie-flat seats and exclusive dining')
    INTO TRAVEL_CLASS ("ID", "NAME", DESCRIPTION) VALUES ('8','Suites','Ultra-luxury private cabins with personal butler service, gourmet dining, and exclusive airport services')
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle CREW_MEMBER
INSERT ALL
    INTO CREW_MEMBER ("ID", FIRSTNAME, LASTNAME, "ROLE", LICENSE_NUMBER, LICENSE_EXPIRY) VALUES ('C001', 'Martin', 'Meier', 'Cabin Crew', 'ABC123', TO_DATE('12-05-27', 'DD-MM-YY'))
    INTO CREW_MEMBER ("ID", FIRSTNAME, LASTNAME, "ROLE", LICENSE_NUMBER, LICENSE_EXPIRY) VALUES ('C002', 'Karolin', 'Becker', 'Cabin Crew', 'DEF123', TO_DATE('25-02-29','DD-MM-YY'))
    INTO CREW_MEMBER ("ID", FIRSTNAME, LASTNAME, "ROLE", LICENSE_NUMBER, LICENSE_EXPIRY) VALUES ('C003', 'Thomas', 'Scheuer', 'Purser', 'GHI456', TO_DATE('10-01-26','DD-MM-YY'))
    INTO CREW_MEMBER ("ID", FIRSTNAME, LASTNAME, "ROLE", LICENSE_NUMBER, LICENSE_EXPIRY) VALUES ('C004', 'Hans', 'Erich', 'Cabin Crew', 'GHI123', TO_DATE('12-12-30','DD-MM-YY'))
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle PLOTTYPE
INSERT ALL
    INTO PLOTTYPE ("ID", "NAME", LABEL) VALUES (1, 'shop', 'Shop')
    INTO PLOTTYPE ("ID", "NAME", LABEL) VALUES (2, 'police', 'Police')
    INTO PLOTTYPE ("ID", "NAME", LABEL) VALUES (3, 'hangar', 'Hangar')
    INTO PLOTTYPE ("ID", "NAME", LABEL) VALUES (4, 'fire', 'Fire Department')
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle PLOT
INSERT ALL
    INTO PLOT ("ID", POSITION, "TYPE" , AREA_SQFT, STATUS, LAST_MAINTENANCE, MAX_WEIGHT_CAPACITY, UTILITIES_AVAILABLE) VALUES ('P001', 1, 1, 400, 'OCCUPIED', TO_DATE('15-12-24','DD-MM-YY'), 5000, 'Water,Electricity,Internet')
    INTO PLOT ("ID", POSITION, "TYPE" , AREA_SQFT, STATUS, LAST_MAINTENANCE, MAX_WEIGHT_CAPACITY, UTILITIES_AVAILABLE) VALUES ('P002', 2, 2, 600, 'OCCUPIED', TO_DATE('20-11-24','DD-MM-YY'), 8000, 'Water,Electricity')
    INTO PLOT ("ID", POSITION, "TYPE" , AREA_SQFT, STATUS, LAST_MAINTENANCE, MAX_WEIGHT_CAPACITY, UTILITIES_AVAILABLE) VALUES ('P003', 3, 3, 1200, 'MAINTENANCE', TO_DATE('05-01-25','DD-MM-YY'), 12000, 'Water,Electricity,Internet,Gas')
    INTO PLOT ("ID", POSITION, "TYPE" , AREA_SQFT, STATUS, LAST_MAINTENANCE, MAX_WEIGHT_CAPACITY, UTILITIES_AVAILABLE) VALUES ('P004', 4, 4, 400, 'OCCUPIED', TO_DATE('01-12-24','DD-MM-YY'), 5000, 'Water,Electricity')
    INTO PLOT ("ID", POSITION, "TYPE" , AREA_SQFT, STATUS, LAST_MAINTENANCE, MAX_WEIGHT_CAPACITY, UTILITIES_AVAILABLE) VALUES ('P005', 5, 3, 800, 'OCCUPIED', TO_DATE('30-10-24','DD-MM-YY'), 10000, 'Water,Electricity,Internet')
    INTO PLOT ("ID", POSITION, "TYPE" , AREA_SQFT, STATUS, LAST_MAINTENANCE, MAX_WEIGHT_CAPACITY, UTILITIES_AVAILABLE) VALUES ('P006', 6, 4, 800, 'AVAILABLE', TO_DATE('30-11-24','DD-MM-YY'), 1000, 'Water,Electricity,Internet')
SELECT 1 FROM DUAL;

-- MISSING HANGAR
INSERT ALL
    INTO HANGAR ("ID", PLOT, CAPACITY, SIZE_SQFT, STATUS, LAST_INSPECTION, NEXT_INSPECTION) VALUES ('H001', 'P003', 10, 1200, 'MAINTENANCE', TO_DATE('12-01-20','DD-MM-YY'), TO_DATE('01-01-25','DD-MM-YY'))
    INTO HANGAR ("ID", PLOT, CAPACITY, SIZE_SQFT, STATUS, LAST_INSPECTION, NEXT_INSPECTION) VALUES ('H002', 'P005', 10, 800, 'ACTIVE', TO_DATE('5-03-22','DD-MM-YY'), TO_DATE('10-03-27','DD-MM-YY'))
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle PILOT
INSERT ALL
    INTO PILOT ("ID", FIRSTNAME, LASTNAME, FLIGHT_HOURS, LICENSE_TYPE, LICENSE_NUMBER, LICENSE_EXPIRY) VALUES ('PIL001', 'James', 'Anderson', 1450, 'ATPL-A', '123', TO_DATE('31-12-2030', 'dd-mm-yyyy'))
    INTO PILOT ("ID", FIRSTNAME, LASTNAME, FLIGHT_HOURS, LICENSE_TYPE, LICENSE_NUMBER, LICENSE_EXPIRY) VALUES ('PIL002', 'Emily', 'Davis', 430, 'ATPL-A', '456', TO_DATE('31-12-2030', 'dd-mm-yyyy'))
    INTO PILOT ("ID", FIRSTNAME, LASTNAME, FLIGHT_HOURS, LICENSE_TYPE, LICENSE_NUMBER, LICENSE_EXPIRY) VALUES ('PIL003', 'William', 'Taylor', 1540, 'ATPL-A', '789', TO_DATE('31-12-2030', 'dd-mm-yyyy'))
    INTO PILOT ("ID", FIRSTNAME, LASTNAME, FLIGHT_HOURS, LICENSE_TYPE, LICENSE_NUMBER, LICENSE_EXPIRY) VALUES ('PIL004', 'Sophia', 'Wilson', 2430, 'ATPL-A', '101', TO_DATE('31-12-2030', 'dd-mm-yyyy'))
    INTO PILOT ("ID", FIRSTNAME, LASTNAME, FLIGHT_HOURS, LICENSE_TYPE, LICENSE_NUMBER, LICENSE_EXPIRY) VALUES ('PIL005', 'Daniel', 'Martin', 270, 'CPL', '112', TO_DATE('31-12-2030', 'dd-mm-yyyy'))
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle PLANE
INSERT ALL
    INTO PLANE ("ID", MODEL, SEATS, AIRLINE, MANUFACTURING_YEAR, MAX_TAKEOFF_WEIGHT, FUEL_CAPACITY, STATUS) VALUES ('P001', 'Boeing 747-800', 467, 'LH', 2015, 442300, 184000, 'ACTIVE')
    INTO PLANE ("ID", MODEL, SEATS, AIRLINE, MANUFACTURING_YEAR, MAX_TAKEOFF_WEIGHT, FUEL_CAPACITY, STATUS) VALUES ('P002', 'Airbus A320', 180, 'LH', 1998, 77000, 16000, 'ACTIVE')
    INTO PLANE ("ID", MODEL, SEATS, AIRLINE, MANUFACTURING_YEAR, MAX_TAKEOFF_WEIGHT, FUEL_CAPACITY, STATUS) VALUES ('P003', 'Boeing 777-300ER', 294, 'AF', 2014, 352000, 190500, 'ACTIVE')
    INTO PLANE ("ID", MODEL, SEATS, AIRLINE, MANUFACTURING_YEAR, MAX_TAKEOFF_WEIGHT, FUEL_CAPACITY, STATUS) VALUES ('P004', 'Airbus A380', 509, 'EK', 2015, 569000, 250000, 'ACTIVE')
    INTO PLANE ("ID", MODEL, SEATS, AIRLINE, MANUFACTURING_YEAR, MAX_TAKEOFF_WEIGHT, FUEL_CAPACITY, STATUS) VALUES ('P005', 'Boeing 777-300ER', 294, 'UA', 2020, 352000, 190500, 'ACTIVE')
    INTO PLANE ("ID", MODEL, SEATS, AIRLINE, MANUFACTURING_YEAR, MAX_TAKEOFF_WEIGHT, FUEL_CAPACITY, STATUS) VALUES ('P006', 'Airbus A320', 180, 'AF', 2012, 77000, 16000, 'ACTIVE')
    INTO PLANE ("ID", MODEL, SEATS, AIRLINE, MANUFACTURING_YEAR, MAX_TAKEOFF_WEIGHT, FUEL_CAPACITY, STATUS, HANGAR) VALUES ('P007', 'Boeing 737-700', 143, 'EK', 2016, 70000, 20800, 'MAINTENANCE', 'H002')
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle MAINTENANCE_LOG
INSERT ALL
    INTO MAINTENANCE_LOG ("ID", PLANE, MAINTENANCE_DATE, TECHNICIAN, DESCRIPTION, NEXT_MAINTENANCE) VALUES ('M001', 'P001', TO_DATE('15-12-24', 'DD-MM-YY'), 'Tech001', 'Engine check', TO_DATE('15-07-25', 'DD-MM-YY'))
    INTO MAINTENANCE_LOG ("ID", PLANE, MAINTENANCE_DATE, TECHNICIAN, DESCRIPTION, NEXT_MAINTENANCE) VALUES ('M002', 'P002', TO_DATE('10-11-24', 'DD-MM-YY'), 'Tech002', 'Landing gear repair', TO_DATE('10-05-25', 'DD-MM-YY'))
    INTO MAINTENANCE_LOG ("ID", PLANE, MAINTENANCE_DATE, TECHNICIAN, DESCRIPTION, NEXT_MAINTENANCE) VALUES ('M003', 'P003', TO_DATE('20-10-24', 'DD-MM-YY'), 'Tech003', 'Fuel system inspection', TO_DATE('20-04-25', 'DD-MM-YY'))
    INTO MAINTENANCE_LOG ("ID", PLANE, MAINTENANCE_DATE, TECHNICIAN, DESCRIPTION, NEXT_MAINTENANCE) VALUES ('M004', 'P004', TO_DATE('25-07-24', 'DD-MM-YY'), 'Tech004', 'Cabin overhaul', TO_DATE('25-03-25', 'DD-MM-YY'))
    INTO MAINTENANCE_LOG ("ID", PLANE, MAINTENANCE_DATE, TECHNICIAN, DESCRIPTION, NEXT_MAINTENANCE) VALUES ('M005', 'P005', TO_DATE('26-07-24', 'DD-MM-YY'), 'Tech005', 'Wing structure inspection', TO_DATE('28-03-25', 'DD-MM-YY'))
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle FLIGHT
INSERT ALL
    INTO FLIGHT ("ID", "FROM", "TO", PILOT, PLANE, SCHEDULED_DEPARTURE, ACTUAL_DEPARTURE, SCHEDULED_ARRIVAL, ACTUAL_ARRIVAL, STATUS) VALUES ('F001', 'CDG', 'MIN', 'PIL001', 'P003', TO_TIMESTAMP('01-JAN-25 10:00:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('01-JAN-25 10:05:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('01-JAN-25 13:45:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('01-JAN-25 13:50:00', 'DD-MON-YY HH24:MI:SS'), 1)
    INTO FLIGHT ("ID", "FROM", "TO", PILOT, PLANE, SCHEDULED_DEPARTURE, ACTUAL_DEPARTURE, SCHEDULED_ARRIVAL, ACTUAL_ARRIVAL, STATUS) VALUES ('F002', 'MUC', 'MIN', 'PIL002', 'P002', TO_TIMESTAMP('02-JAN-25 08:00:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('02-JAN-25 09:15:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('02-JAN-25 10:00:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('16-JAN-25 11:30:00', 'DD-MON-YY HH24:MI:SS'), 5)
    INTO FLIGHT ("ID", "FROM", "TO", PILOT, PLANE, SCHEDULED_DEPARTURE, ACTUAL_DEPARTURE, SCHEDULED_ARRIVAL, ACTUAL_ARRIVAL, STATUS) VALUES ('F003', 'MIN', 'MUC', 'PIL002', 'P002', TO_TIMESTAMP('02-JAN-25 13:00:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('02-JAN-25 12:55:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('02-JAN-25 15:00:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('02-JAN-25 15:00:00', 'DD-MON-YY HH24:MI:SS'), 1)
    INTO FLIGHT ("ID", "FROM", "TO", PILOT, PLANE, SCHEDULED_DEPARTURE, ACTUAL_DEPARTURE, SCHEDULED_ARRIVAL, ACTUAL_ARRIVAL, STATUS) VALUES ('F004', 'MIN', 'JFK', 'PIL004', 'P004', TO_TIMESTAMP('02-JAN-25 23:00:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('02-JAN-25 23:00:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('03-JAN-25 10:00:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('03-JAN-25 10:10:00', 'DD-MON-YY HH24:MI:SS'), 1)
    INTO FLIGHT ("ID", "FROM", "TO", PILOT, PLANE, SCHEDULED_DEPARTURE, ACTUAL_DEPARTURE, SCHEDULED_ARRIVAL, ACTUAL_ARRIVAL, STATUS) VALUES ('F005', 'CDG', 'MIN', 'PIL003', 'P004', TO_TIMESTAMP('01-JAN-25 13:00:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('01-JAN-25 14:00:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('03-JAN-25 14:35:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('03-JAN-25 15:35:00', 'DD-MON-YY HH24:MI:SS'), 5)
    INTO FLIGHT ("ID", "FROM", "TO", PILOT, PLANE, SCHEDULED_DEPARTURE, ACTUAL_DEPARTURE, SCHEDULED_ARRIVAL, ACTUAL_ARRIVAL, STATUS) VALUES ('F006', 'MIN', 'CDG', 'PIL003', 'P004', TO_TIMESTAMP('01-JAN-25 15:30:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('01-JAN-25 16:15:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('03-JAN-25 16:45:00', 'DD-MON-YY HH24:MI:SS'), TO_TIMESTAMP('03-JAN-25 17:30:00', 'DD-MON-YY HH24:MI:SS'), 5)
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle FLIGHT_CREW
INSERT ALL
    INTO FLIGHT_CREW ("ID", FLIGHT, CREW_MEMBER, "ROLE") VALUES ('FC001', 'F002', 'C001', 'Cabin Crew')
    INTO FLIGHT_CREW ("ID", FLIGHT, CREW_MEMBER, "ROLE") VALUES ('FC002', 'F002', 'C002', 'Cabin Crew')
    INTO FLIGHT_CREW ("ID", FLIGHT, CREW_MEMBER, "ROLE") VALUES ('FC003', 'F002', 'C003', 'Purser')
    INTO FLIGHT_CREW ("ID", FLIGHT, CREW_MEMBER, "ROLE") VALUES ('FC004', 'F002', 'C004', 'Cabin Crew')
SELECT 1 FROM DUAL;

--  Beispiel-Datensätze für die Tabelle SHOPTYPE
INSERT ALL 
    INTO SHOPTYPE ("ID", "NAME", LABEL, CATEGORY, SECURITY_LEVEL, DESCRIPTION, TYPICAL_HOURS) VALUES ('PT001', 'Coffee House Express', 'CHE', 'Food', 'PRE_SECURITY', 'Quick-service coffee shop offering premium beverages, pastries, and light snacks', '5:00 AM - 9:00 PM')
    INTO SHOPTYPE ("ID", "NAME", LABEL, CATEGORY, SECURITY_LEVEL, DESCRIPTION, TYPICAL_HOURS) VALUES ('PT002', 'Global News', 'GNG', 'Retail', 'POST_SECURITY', 'Newsstand and convenience store offering magazines, snacks, travel essentials, and local souvenirs', '6:00 AM - 10:00 PM')
    INTO SHOPTYPE ("ID", "NAME", LABEL, CATEGORY, SECURITY_LEVEL, DESCRIPTION, TYPICAL_HOURS) VALUES ('PT003', 'Luxury Fashion Boutique', 'LFB', 'Fashion', 'POST_SECURITY', 'High-end fashion retailer featuring designer clothing, accessories, and luxury goods', '8:00 AM - 8:00 PM')
    INTO SHOPTYPE ("ID", "NAME", LABEL, CATEGORY, SECURITY_LEVEL, DESCRIPTION, TYPICAL_HOURS) VALUES ('PT004', 'Quick Bites Deli', 'QBD', 'Food', 'POST_SECURITY', 'Fresh sandwiches, salads, and grab-and-go meals for travelers', '6:00 AM - 9:00 PM')
    INTO SHOPTYPE ("ID", "NAME", LABEL, CATEGORY, SECURITY_LEVEL, DESCRIPTION, TYPICAL_HOURS) VALUES ('PT005', 'Tech', 'TEC', 'Electronics', 'PRE_SECURITY', 'Electronics store offering gadgets, accessories, and travel technology essentials', '7:00 AM - 9:00 PM')
    INTO SHOPTYPE ("ID", "NAME", LABEL, CATEGORY, SECURITY_LEVEL, DESCRIPTION, TYPICAL_HOURS) VALUES ('PT006', 'International Dining', 'IND', 'Food ','POST_SECURITY', 'Full-service restaurant featuring a diverse menu of international cuisine', '10:00 AM - 10:00 PM')
    INTO SHOPTYPE ("ID", "NAME", LABEL, CATEGORY, SECURITY_LEVEL, DESCRIPTION, TYPICAL_HOURS) VALUES ('PT007', 'Travel Essentials', 'TRE', 'Retail', 'PRE_SECURITY', 'One-stop shop for travel necessities, toiletries, and convenience items', '24 hours')
    INTO SHOPTYPE ("ID", "NAME", LABEL, CATEGORY, SECURITY_LEVEL, DESCRIPTION, TYPICAL_HOURS) VALUES ('PT008', 'Duty Free Shop', 'DFS', 'Retail', 'POST_SECURITY', 'Tax-free shopping featuring premium spirits, cosmetics, and luxury goods', '6:00 AM - 11:00 PM')
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle SHOP
INSERT ALL
    INTO SHOP ("ID", "NAME", "TYPE", PLOT, IS_DUTY_FREE) VALUES ('S001', 'Duty Free Shop', 'PT008', 'P001', 1)
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle TERMINAL
INSERT ALL
    INTO TERMINAL ("ID", "NAME", CAPACITY, FLOOR_COUNT, SERVICES) VALUES ('T001', 'Terminal 1', 200, 1, 'Baggage Handling, Fueling')
    INTO TERMINAL ("ID", "NAME", CAPACITY, FLOOR_COUNT, SERVICES) VALUES ('T002', 'Terminal 2', 400, 1, 'Baggage Handling, Fueling, Line Maintenance')
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle AIRPORTUSER
INSERT ALL
    INTO AIRPORTUSER ("ID", FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL, "PASSWORD", PHONE, ACTIVE, ROLE) VALUES ('1c2c398a-9f0a-40b8-acac-c409e7388865', 'John', 'Doe', TO_DATE('15-07-85','dd-mm-yy'), 'johndoe@example.com', '$2a$12$iiwKC1xGjorArDxb5bcDnu6BRiihvhDf2vhj1Fqoszrj3vD3pgSzu', '1234567890', 1, 'ADMIN')
    INTO AIRPORTUSER ("ID", FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL, "PASSWORD", PHONE, ACTIVE) VALUES ('db6417cd-03f2-4578-bf0b-b72c20528c47', 'Jane', 'Smith', TO_DATE('25-09-90','dd-mm-yy'), 'janesmith@example.com', '$2a$10$MRvssDzwuqWxV/FkN1KOzeraYA92LqkW1.PjqC2VmenJf.U2puok.', '0987654321', 1)
    INTO AIRPORTUSER ("ID", FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL, "PASSWORD", PHONE, ACTIVE) VALUES ('1f74c4b9-2d46-452b-8463-c8cce3d20abe', 'Michael', 'Brown', TO_DATE('10-03-82','dd-mm-yy'), 'michaelbrown@example.com', '$2a$10$MRvssDzwuqWxV/FkN1KOzeraYA92LqkW1.PjqC2VmenJf.U2puok.', '1122334455', 1)
    INTO AIRPORTUSER ("ID", FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL, "PASSWORD", PHONE, ACTIVE) VALUES ('025a9b69-7f87-47ea-90b0-0c1fa4b23dd7', 'Emily', 'Johnson', TO_DATE('30-07-95','dd-mm-yy'), 'emilyjohnson@example.com', '$2a$10$MRvssDzwuqWxV/FkN1KOzeraYA92LqkW1.PjqC2VmenJf.U2puok.', '9988776655', 1)
    INTO AIRPORTUSER ("ID", FIRSTNAME, LASTNAME, BIRTHDATE, EMAIL, "PASSWORD", PHONE, ACTIVE) VALUES ('62620fcc-cf34-46b2-9e62-0c175deb9574', 'Sarah', 'Lee', TO_DATE('15-01-98','dd-mm-yy'), 'sarahlee@example.com', '$2a$10$MRvssDzwuqWxV/FkN1KOzeraYA92LqkW1.PjqC2VmenJf.U2puok.', '5566778899', 1)
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle BAGGAGE
INSERT ALL
    INTO BAGGAGE ("ID", AIRPORTUSER, FLIGHT, "SIZE", WEIGHT, TRACKING_NUMBER, STATUS, SPECIAL_HANDLING) VALUES ('B001', '1c2c398a-9f0a-40b8-acac-c409e7388865', 'F001', 1, 23.5, 'TRACK123', 'CHECKED', 'None')
    INTO BAGGAGE ("ID", AIRPORTUSER, FLIGHT, "SIZE", WEIGHT, TRACKING_NUMBER, STATUS, SPECIAL_HANDLING) VALUES ('B002', 'db6417cd-03f2-4578-bf0b-b72c20528c47', 'F002', 2, 32.75, 'TRACK456', 'IN_TRANSIT', 'Fragile')
    INTO BAGGAGE ("ID", AIRPORTUSER, FLIGHT, "SIZE", WEIGHT, TRACKING_NUMBER, STATUS, SPECIAL_HANDLING) VALUES ('B003', '1f74c4b9-2d46-452b-8463-c8cce3d20abe', 'F003', 3, 45, 'TRACK789', 'CHECKED', 'Oversized')
    INTO BAGGAGE ("ID", AIRPORTUSER, FLIGHT, "SIZE", WEIGHT, TRACKING_NUMBER, STATUS, SPECIAL_HANDLING) VALUES ('B004', '025a9b69-7f87-47ea-90b0-0c1fa4b23dd7', 'F004', 1, 18.25, 'TRACK101', 'IN_TRANSIT', 'None')
    INTO BAGGAGE ("ID", AIRPORTUSER, FLIGHT, "SIZE", WEIGHT, TRACKING_NUMBER, STATUS, SPECIAL_HANDLING) VALUES ('B005', '62620fcc-cf34-46b2-9e62-0c175deb9574', 'F005', 1, 20.5, 'TRACK112', 'IN_TRANSIT', 'None')
SELECT 1 FROM DUAL;

-- Beispiel-Datensätze für die Tabelle TICKET
INSERT ALL
    INTO TICKET ("ID", AIRPORTUSER, FLIGHT, SEAT_NUMBER, TRAVEL_CLASS, BOOKING_DATE, STATUS, PRICE, BOOKING_DATE) VALUES ('T001', '1c2c398a-9f0a-40b8-acac-c409e7388865', 'F001', '12A', '4', '2025-1-1', 'CONFIRMED', 120, TO_DATE('01-01-25','dd-mm-yy'))
    INTO TICKET ("ID", AIRPORTUSER, FLIGHT, SEAT_NUMBER, TRAVEL_CLASS, BOOKING_DATE, STATUS, PRICE, BOOKING_DATE) VALUES ('T002', 'db6417cd-03f2-4578-bf0b-b72c20528c47', 'F002', '5B', '2', '2024-11-24', 'CONFIRMED', 200, TO_DATE('24-11-24','dd-mm-yy'))
    INTO TICKET ("ID", AIRPORTUSER, FLIGHT, SEAT_NUMBER, TRAVEL_CLASS, BOOKING_DATE, STATUS, PRICE, BOOKING_DATE) VALUES ('T003', '1f74c4b9-2d46-452b-8463-c8cce3d20abe', 'F003', '20C', '1', '2024-12-01', 'CONFIRMED', 130, TO_DATE('13-01-25','dd-mm-yy'))
    INTO TICKET ("ID", AIRPORTUSER, FLIGHT, SEAT_NUMBER, TRAVEL_CLASS, BOOKING_DATE, STATUS, PRICE, BOOKING_DATE) VALUES ('T004', '025a9b69-7f87-47ea-90b0-0c1fa4b23dd7', 'F004', '3D', '4', '2025-01-13', 'CONFIRMED', 250, TO_DATE('01-12-24','dd-mm-yy'))
    INTO TICKET ("ID", AIRPORTUSER, FLIGHT, SEAT_NUMBER, TRAVEL_CLASS, BOOKING_DATE, STATUS, PRICE, BOOKING_DATE) VALUES ('T005', '62620fcc-cf34-46b2-9e62-0c175deb9574', 'F005', '15E', '4', '2025-01-14', 'CONFIRMED', 100, TO_DATE('14-01-25','dd-mm-yy'))
SELECT 1 FROM DUAL;